name: train_random_forest
channels:
  - conda-forge
  - defaults
dependencies:
  # - pandas=1.1.4
  - pandas=1.1.4
  - pip=20.3.3
  - mlflow=1.14.1
  - numpy=1.23.4
  - scikit-learn=0.24.1
  - matplotlib=3.2.2
  - pillow=8.1.2
  - pip:
      - wandb==0.10.21
      - protobuf==3.20.3
